project_name: testerific
dist: dist/linux
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
nfpms:
  -
    vendor: "Mondoo, Inc."
    homepage: "https://mondoo.com"
    license: "Proprietary"
    section: "default"
    priority: "extra"
    maintainer: "Ben Rockwood <benr@cuddletech.com>"
    description: |
      This is my testerific test of goreleaser.
      My packaging is dopy dope.
    bindir: /usr/local/bin
    contents:
    - src: testerific
      dst: /usr/local/bin/testerific
    formats:
      - deb
      - rpm
    overrides:
      rpm:
        #provides:
        #  - mondoo({{.arch}})
        #changelog: "changelog.yaml"

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^tmp:'
